import { Geist, Geist_Mono, Hanken_Grotesk, Mulish } from "next/font/google";
import "./globals.css";

export const mulish = Mulish({
  weight: ["400", "500", "700"],
  variable: "--font-mulish", // CSS custom property for Mulish
  subsets: ["latin"],
  display: "swap", // Optional: Ensures font loads with fallback until ready
});
export const hanken = Hanken_Grotesk({
  weight: ["400", "500", "700"],
  variable: "--font-mulish", // CSS custom property for Mulish
  subsets: ["latin"],
  display: "swap", // Optional: Ensures font loads with fallback until ready
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Yaabi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
